const data = {
    products:[
        {   id: 1,
            name: 'Watch',
            image:'https://i.ibb.co/JFPzJ7z/515-00898.jpg',
            category: "Men's watch",
            brand: 'TAG Heuer',
            color: 'black',
            price: 180,
            inStock: 20,
            description: 'A popular watch'
        },
        {   id: 2,
            name: 'Watch',
            image:'https://i.ibb.co/JFPzJ7z/515-00898.jpg',
            category: "Men's watch",
            brand: 'TAG Heuer',
            price: 180,
            color: 'black',
            inStock: 20,
            description: 'A popular watch'
        },
        {   id: 3,
            name: 'Watch',
            image:'https://i.ibb.co/JFPzJ7z/515-00898.jpg',
            category: "Men's watch",
            brand: 'TAG Heuer',
            price: 180,
            color: 'black',
            inStock: 20,
            description: 'A popular watch'
        },
        {   id: 4,
            name: 'Watch',
            image:'https://i.ibb.co/JFPzJ7z/515-00898.jpg',
            category: "Men's watch",
            brand: 'TAG Heuer',
            price: 180,
            color: 'black',
            inStock: 20,
            description: 'A popular watch'
        },
        {   id: 5,
            name: 'Watch',
            image:'https://i.ibb.co/JFPzJ7z/515-00898.jpg',
            category: "Men's watch",
            brand: 'TAG Heuer',
            price: 180,
            color: 'black',
            inStock: 20,
            description: 'A popular watch'
        },
        {   id: 6,
            name: 'Watch',
            image:'https://i.ibb.co/JFPzJ7z/515-00898.jpg',
            category: "Men's watch",
            brand: 'TAG Heuer',
            price: 180,
            color: 'black',
            inStock: 20,
            description: 'A popular watch'
        },
    ]
}
